/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;
import NapakalakiGame.DeathBadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.SpecificBadConsequence;
/**
 *
 * @author Jesús Sánchez de Lechina Tejada & Miguel Ángel Robles Urquiza
 */
public class BadConsequenceView extends javax.swing.JPanel {

    BadConsequence badConsequenceModel;
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }
    
    public void setBadConsequence(BadConsequence bc){
     badConsequenceModel = bc;

     this.text.setText(badConsequenceModel.getText());
     this.level.setText("Niveles a perder:" + Integer.toString(badConsequenceModel.getLevels()));

     if(badConsequenceModel instanceof NumericBadConsequence){
        this.visible.setText("Nº visibles:" + Integer.toString(((NumericBadConsequence)badConsequenceModel).getNVisibleTreasures()));
        this.hidden.setText("Nº ocultos:" + Integer.toString(((NumericBadConsequence)badConsequenceModel).getNHiddenTreasures()));
     }
     else{
        this.visible.setText("");
        this.hidden.setText("");
     }

     if(badConsequenceModel instanceof SpecificBadConsequence){
        this.specificVisible.setText("Visibles específicios:" + ((SpecificBadConsequence)badConsequenceModel).getSpecificVisibleTreasures().toString());
        this.specificHidden.setText("Ocultos específicos:" + ((SpecificBadConsequence)badConsequenceModel).getSpecificHiddenTreasures().toString());
     }
     else{
        this.specificVisible.setText("");
        this.specificHidden.setText("");
     }
     
     if(badConsequenceModel instanceof DeathBadConsequence){
        this.death.setText("¿Le mata? " + PlayerView.boolToSiONo(((DeathBadConsequence)badConsequenceModel).getDeath()));
     }
     else
         this.death.setText("¿Le mata? No");
     repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        text = new javax.swing.JLabel();
        death = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        specificVisible = new javax.swing.JLabel();
        specificHidden = new javax.swing.JLabel();
        visible = new javax.swing.JLabel();
        hidden = new javax.swing.JLabel();

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mal Rollo"));

        text.setText("Mal rollo");

        death.setText("Muerte");

        level.setText("Nivel");

        specificVisible.setText("Tesoros Visibles Especificos");

        specificHidden.setText("Tesoros Ocultos Especificos");

        visible.setText("Tesoros Visibles ");

        hidden.setText("Tesoros Ocultos");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(level)
                        .addGap(59, 59, 59)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(hidden)
                                .addGap(18, 18, 18)
                                .addComponent(specificHidden))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(visible)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(specificVisible)))
                        .addContainerGap(111, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(death)
                            .addComponent(text))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text)
                .addGap(5, 5, 5)
                .addComponent(death)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(specificVisible)
                    .addComponent(level)
                    .addComponent(visible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hidden)
                    .addComponent(specificHidden))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel death;
    private javax.swing.JLabel hidden;
    private javax.swing.JLabel level;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel specificHidden;
    private javax.swing.JLabel specificVisible;
    private javax.swing.JLabel text;
    private javax.swing.JLabel visible;
    // End of variables declaration//GEN-END:variables
}
