/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;
import NapakalakiGame.DeathBadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.SpecificBadConsequence;
/**
 *
 * @author Jesús Sánchez de Lechina Tejada & Miguel Ángel Robles Urquiza
 */
public class BadConsequenceView extends javax.swing.JPanel {

    BadConsequence badConsequenceModel;
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }
    
    public void setBadConsequence(BadConsequence bc){
     badConsequenceModel = bc;

     this.text.setText(badConsequenceModel.getText());
     this.level.setText(Integer.toString(badConsequenceModel.getLevels()));

     if(badConsequenceModel instanceof NumericBadConsequence){
        this.visible.setText(Integer.toString(((NumericBadConsequence)badConsequenceModel).getNVisibleTreasures()));
        this.hidden.setText(Integer.toString(((NumericBadConsequence)badConsequenceModel).getNHiddenTreasures()));
     }

     if(badConsequenceModel instanceof SpecificBadConsequence){
        this.specificVisible.setText(((SpecificBadConsequence)badConsequenceModel).getSpecificVisibleTreasures().toString());
        this.specificHidden.setText(((SpecificBadConsequence)badConsequenceModel).getSpecificHiddenTreasures().toString());
     }
     
     if(badConsequenceModel instanceof DeathBadConsequence){
        this.death.setText(Boolean.toString(((DeathBadConsequence)badConsequenceModel).getDeath()));
     }

     repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        text = new javax.swing.JLabel();
        death = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        specificVisible = new javax.swing.JLabel();
        specificHidden = new javax.swing.JLabel();
        visible = new javax.swing.JLabel();
        hidden = new javax.swing.JLabel();

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mal Rollo"));

        text.setText("Mal rollo");

        death.setText("Muerte");

        level.setText("Nivel");

        specificVisible.setText("Tesoros Visibles Especificos");

        specificHidden.setText("Tesoros Ocultos Especificos");

        visible.setText("Tesoros Visibles ");

        hidden.setText("Tesoros Ocultos");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(level)
                        .addGap(55, 55, 55)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hidden)
                            .addComponent(visible)
                            .addComponent(specificHidden)
                            .addComponent(specificVisible)))
                    .addComponent(death)))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(death)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(level)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(specificVisible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(specificHidden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hidden)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel death;
    private javax.swing.JLabel hidden;
    private javax.swing.JLabel level;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel specificHidden;
    private javax.swing.JLabel specificVisible;
    private javax.swing.JLabel text;
    private javax.swing.JLabel visible;
    // End of variables declaration//GEN-END:variables
}
